name: model_house
description: "UI Library for Flutter and Firebase to build app quickly"
version: 0.0.2
homepage: https://github.com/thruthesky/model_house

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: 5.0.2
  cloud_functions: 5.0.2
  date_picker_v2: ^0.0.2
  devicelocale: ^0.7.1
  firebase_auth: 5.1.1
  firebase_core: 3.1.1
  firebase_database: 11.0.2
  firebase_messaging: 15.0.2
  firebase_storage: 12.1.0
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter
  memory_cache: ^1.2.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
